#!/usr/bin/env python
# -*- coding: utf-8 -*- 
training_data = []
training_data.append({"class":"positive","sentence": "Judy Garland is perfectly cast as Dorothy. She is as clever a little actress as she is a singer and her special style of vocalizing is ideally adapted to the music of the picture."})
training_data.append({"class":"positive","sentence": "In truth, any opportunity to see the film on the big screen is welcome."})
training_data.append({"class":"positive","sentence": "The greatest American movie fantasy."})
training_data.append({"class":"positive","sentence": "The blend of old-fashioned, classic storytelling with cutting-edge technology is undeniably enthralling."})
training_data.append({"class":"positive","sentence": "The result is quite stunning and a lot less gimmicky than it could have been."})
training_data.append({"class":"positive","sentence": "It is a triumph of the film, and proof of its solid value and of the sense of its director and all concerned, that a human touch is not lost. Sympathy for the preposterous Mr. Kane survives. Indeed, there is something about him which seems admirable."})
training_data.append({"class":"positive","sentence": "Welles' performance is nothing less than astonishing. He begins as a youth of 21, goes through middle age to his death, and makes every moment believable in voice, walk, and gesture. Even in his love scenes is Welles effective."})
training_data.append({"class":"positive","sentence": "This stuff is fine theatre, technically or any other way, and along with them the film is exciting for the recklessness of its independence, even if it seems to have little to be free for."})
training_data.append({"class":"positive","sentence": "Some day, and the time won't be long in arriving, Welles will be the greatest director in Hollywood."})
training_data.append({"class":"positive","sentence": "It can be classified as, in a number of aspects, one of the most arresting pictures ever produced."})
training_data.append({"class":"positive","sentence": "A case can be made that Caligari was the first true horror film."})
training_data.append({"class":"positive","sentence": "Undoubtedly one of the most exciting and inspired horror movies ever made."})
training_data.append({"class":"positive","sentence": "The Cabinet of Dr. Caligari is one of cinema's most enduring masterpieces."})
training_data.append({"class":"positive","sentence": "All About Eve is not only a brilliant and clever portrait of an actress, it is a downright funny film, from its opening scene to the final fadeout."})
training_data.append({"class":"positive","sentence": "It crackles with smart, smarting dialogue."})
training_data.append({"class":"positive","sentence": "Believe all the hype: This movie will melt your face off."})
training_data.append({"class":"positive","sentence": "One of the many remarkable things about Charlie Chaplin is that his films continue to hold up, to attract and delight audiences."})
training_data.append({"class":"positive","sentence": "The picture is grand fun and sound entertainment, though silent. It's the old Chaplin at his best, looking at his best "})
training_data.append({"class":"positive","sentence": "One of the shining glories of the American musical."})
training_data.append({"class":"positive","sentence": "If you've never seen it and don't, you're bonkers."})
training_data.append({"class":"positive","sentence": "i like and loved it"})
training_data.append({"class":"positive","sentence": "you should definately watch it"})
training_data.append({"class":"positive","sentence": "I love this movie. The best movie I have ever scene"})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})


training_data.append({"class":"negitive","sentence": "I'd rather wake up next to a severed horse head than ever watch Gotti again."})
training_data.append({"class":"negitive","sentence": "full time waste"})
training_data.append({"class":"negitive","sentence": "they haven not did justice to the roles and actors"})
training_data.append({"class":"negitive","sentence": "the movie was so slow and boring that you will easily fall asleep"})
training_data.append({"class":"negitive","sentence": "it was not good"})
training_data.append({"class":"negitive","sentence": "He looks distractingly terrible at every stop...You never forget that you are watching John Travolta playing John Gotti every time."})
training_data.append({"class":"negitive","sentence": "Gotti tries too hard to cram too much information into a small space, and you come away learning almost nothing about the man, other than the filmmakers feel he was a pretty stand-up guy."})
training_data.append({"class":"negitive","sentence": "It's not a good movie. But the blame can't be laid at its star's Ferragamo-shod feet."})
training_data.append({"class":"negitive","sentence": "this was a big flop"})
training_data.append({"class":"negitive","sentence": "that was full of shit and why i am not dead before seeing all this "})
training_data.append({"class":"negitive","sentence": "The recut American version is truly awful, but a good 75 percent of the awfulness is attributable to Miramax, the film's distributor."})
training_data.append({"class":"negitive","sentence": "it was a huge disaster and an awful dream i want my money back"})
training_data.append({"class":"negitive","sentence": "Boring, terrible and the begining of Travolta's decline."})
training_data.append({"class":"negitive","sentence": "What a great shame that such a talented director as Chen Kaige has chosen to make his English-language debut with a film so poorly plotted and scripted."})
training_data.append({"class":"negitive","sentence": "A boring and garish mess that even fans of the book will find nearly impossible to follow."})
training_data.append({"class":"negitive","sentence": "Quite simply, horrendous - a trashy, tortured misfire from beginning to end."})
training_data.append({"class":"negitive","sentence": "silly premise but it is fun at times when they aren't cutting budget constraints. the ending sucks"})
training_data.append({"class":"negitive","sentence": "Brainless and pointless."})
training_data.append({"class":"negitive","sentence": "Tries too hard to be madcap."})
training_data.append({"class":"negitive","sentence": "It is often impossible to figure out what's going on."})
training_data.append({"class":"negitive","sentence": "i don't like it"})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})
#training_data.append({"class":"","sentence": ""})

print ("%s sentences of training data" % len(training_data))
